"""Exchange name → country / ISO code / lat-lon centroid."""

_FALLBACK = {"country": "Other", "code": "XX", "lat": 0.0, "lon": 0.0}

EXCHANGE_MAP: dict[str, dict] = {
    "NYSE Consolidated":                    {"country": "United States", "code": "US", "lat": 37.0, "lon": -95.7},
    "NASDAQ Global Select Consolidated":    {"country": "United States", "code": "US", "lat": 37.0, "lon": -95.7},
    "NASDAQ Global Market Consolidated":    {"country": "United States", "code": "US", "lat": 37.0, "lon": -95.7},
    "NASDAQ Capital Market Consolidated":   {"country": "United States", "code": "US", "lat": 37.0, "lon": -95.7},
    "NYSE American Consolidated":           {"country": "United States", "code": "US", "lat": 37.0, "lon": -95.7},
    "Cboe Consolidated":                    {"country": "United States", "code": "US", "lat": 37.0, "lon": -95.7},
    "Shanghai Stock Exchange":              {"country": "China", "code": "CN", "lat": 35.0, "lon": 105.0},
    "Shenzhen Stock Exchange":              {"country": "China", "code": "CN", "lat": 35.0, "lon": 105.0},
    "Tokyo Stock Exchange":                 {"country": "Japan", "code": "JP", "lat": 36.2, "lon": 138.3},
    "National Stock Exchange of India":     {"country": "India", "code": "IN", "lat": 20.6, "lon": 79.0},
    "The Stock Exchange of Hong Kong Ltd":  {"country": "Hong Kong", "code": "HK", "lat": 22.3, "lon": 114.2},
    "The Toronto Stock Exchange":           {"country": "Canada", "code": "CA", "lat": 56.1, "lon": -106.3},
    "London Stock Exchange":                {"country": "United Kingdom", "code": "GB", "lat": 55.4, "lon": -3.4},
    "Euronext Paris":                       {"country": "France", "code": "FR", "lat": 46.6, "lon": 1.9},
    "Euronext Amsterdam":                   {"country": "Netherlands", "code": "NL", "lat": 52.1, "lon": 5.3},
    "Euronext Brussels":                    {"country": "Belgium", "code": "BE", "lat": 50.5, "lon": 4.5},
    "Euronext Lisbon":                      {"country": "Portugal", "code": "PT", "lat": 39.4, "lon": -8.2},
    "Taiwan Stock Exchange":                {"country": "Taiwan", "code": "TW", "lat": 23.7, "lon": 121.0},
    "Taipei Exchange":                      {"country": "Taiwan", "code": "TW", "lat": 23.7, "lon": 121.0},
    "Xetra":                                {"country": "Germany", "code": "DE", "lat": 51.2, "lon": 10.5},
    "Frankfurt Stock Exchange":             {"country": "Germany", "code": "DE", "lat": 51.2, "lon": 10.5},
    "Korea Exchange - KSE":                 {"country": "South Korea", "code": "KR", "lat": 35.9, "lon": 127.8},
    "Korea Exchange - KOSDAQ":              {"country": "South Korea", "code": "KR", "lat": 35.9, "lon": 127.8},
    "SIX Swiss Exchange":                   {"country": "Switzerland", "code": "CH", "lat": 46.8, "lon": 8.2},
    "Australian Stock Exchange Ltd":        {"country": "Australia", "code": "AU", "lat": -25.3, "lon": 134.8},
    "Singapore Exchange Securities Trading Ltd": {"country": "Singapore", "code": "SG", "lat": 1.4, "lon": 103.8},
    "Milan Stock Exchange":                 {"country": "Italy", "code": "IT", "lat": 41.9, "lon": 12.6},
    "BME SPANISH EXCHANGE":                 {"country": "Spain", "code": "ES", "lat": 40.5, "lon": -3.7},
    "OMX Nordic Exchange Stockholm AB - cash": {"country": "Sweden", "code": "SE", "lat": 60.1, "lon": 18.6},
    "OMX Nordic Exchange Copenhagen A/S":   {"country": "Denmark", "code": "DK", "lat": 56.3, "lon": 9.5},
    "OMX Nordic Exchange Helsinki Oy":      {"country": "Finland", "code": "FI", "lat": 61.9, "lon": 25.7},
    "Oslo Stock Exchange":                  {"country": "Norway", "code": "NO", "lat": 60.5, "lon": 8.5},
    "Vienna Stock Exchange - Cash Market":  {"country": "Austria", "code": "AT", "lat": 47.5, "lon": 14.6},
    "Warsaw Stock Exchange":                {"country": "Poland", "code": "PL", "lat": 51.9, "lon": 19.1},
    "Budapest Stock Exchange":              {"country": "Hungary", "code": "HU", "lat": 47.2, "lon": 19.5},
    "Bucharest Stock Exchange":             {"country": "Romania", "code": "RO", "lat": 45.9, "lon": 25.0},
    "Athens Stock Exchange":                {"country": "Greece", "code": "GR", "lat": 39.1, "lon": 21.8},
    "The Irish Stock Exchange":             {"country": "Ireland", "code": "IE", "lat": 53.1, "lon": -7.7},
    "BORSA ISTANBUL":                       {"country": "Turkey", "code": "TR", "lat": 38.9, "lon": 35.2},
    "Tel Aviv Stock Exchange":              {"country": "Israel", "code": "IL", "lat": 31.0, "lon": 34.9},
    "Saudi Arabian Stock Exchange":         {"country": "Saudi Arabia", "code": "SA", "lat": 23.9, "lon": 45.1},
    "Abu Dhabi Stock Exchange":             {"country": "United Arab Emirates", "code": "AE", "lat": 23.4, "lon": 53.8},
    "Dubai Financial Market":               {"country": "United Arab Emirates", "code": "AE", "lat": 23.4, "lon": 53.8},
    "QATAR EXCHANGE LEVEL 1":               {"country": "Qatar", "code": "QA", "lat": 25.4, "lon": 51.2},
    "Boursa Kuwait":                        {"country": "Kuwait", "code": "KW", "lat": 29.3, "lon": 47.5},
    "Muscat Securities Market":             {"country": "Oman", "code": "OM", "lat": 21.5, "lon": 55.9},
    "Amman Financial Market":               {"country": "Jordan", "code": "JO", "lat": 30.6, "lon": 36.2},
    "Johannesburg Stock Exchange":          {"country": "South Africa", "code": "ZA", "lat": -30.6, "lon": 22.9},
    "Nigerian Stock Exchange":              {"country": "Nigeria", "code": "NG", "lat": 9.1, "lon": 8.7},
    "Casablanca Stock Exchange":            {"country": "Morocco", "code": "MA", "lat": 31.8, "lon": -7.1},
    "BM&F Bovespa SA Bolsa de Valores Mercadorias e Futuros": {"country": "Brazil", "code": "BR", "lat": -14.2, "lon": -51.9},
    "Bolsa Mexicana de Valores S.A. de C.V.":                 {"country": "Mexico", "code": "MX", "lat": 23.6, "lon": -102.6},
    "Bolsa de Comercio de Buenos Aires":    {"country": "Argentina", "code": "AR", "lat": -38.4, "lon": -63.6},
    "Bolsa de Comercio de Santiago":        {"country": "Chile", "code": "CL", "lat": -35.7, "lon": -71.5},
    "Bolsa de Valores de Colombia":         {"country": "Colombia", "code": "CO", "lat": 4.6, "lon": -74.3},
    "Bolsa de Valores de Lima S.A.":        {"country": "Peru", "code": "PE", "lat": -9.2, "lon": -75.0},
    "Indonesia Stock Exchange (formerly Jakarta SE)": {"country": "Indonesia", "code": "ID", "lat": -0.8, "lon": 113.9},
    "Bursa Malaysia":                       {"country": "Malaysia", "code": "MY", "lat": 4.2, "lon": 101.9},
    "The Stock Exchange of Thailand":       {"country": "Thailand", "code": "TH", "lat": 15.9, "lon": 100.9},
    "Philippine Stock Exchange, Inc":       {"country": "Philippines", "code": "PH", "lat": 12.9, "lon": 121.8},
    "PSE CASH MARKET L1 AND L2":            {"country": "Philippines", "code": "PH", "lat": 12.9, "lon": 121.8},
    "Hochiminh Stock Exchange":             {"country": "Vietnam", "code": "VN", "lat": 14.1, "lon": 108.3},
    "New Zealand Stock Exchange":           {"country": "New Zealand", "code": "NZ", "lat": -40.9, "lon": 174.9},
    "Kazakhstan Stock Exchange":            {"country": "Kazakhstan", "code": "KZ", "lat": 48.0, "lon": 68.0},
    "Beirut Stock Exchange":                {"country": "Lebanon", "code": "LB", "lat": 33.9, "lon": 35.9},
}


def lookup(exchange: str) -> dict:
    """Return country info for an exchange name. Falls back to 'Other' if unmapped."""
    return EXCHANGE_MAP.get(exchange, _FALLBACK)
